version: '3.8'

services:
  node_backend:
    container_name: node_api
    image: node_api:0.1.2
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=3000
      - PGDATABASE=flats_db
      - PGUSER=flats
      - PGPASSWORD=12345
      - PGHOST=node_db 
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=flats
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=flats_db
    volumes:
      - ./app/data:/var/lib/postgresql/database/pgdata
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}